
export const TEXTURE_CATEGORY = `./SC-Textures`;
export const TEXTURE_IN_SC = `${TEXTURE_CATEGORY}/In-SC-Textures`;
export const TEXTURE_IN = `${TEXTURE_CATEGORY}/In-Textures`;
export const TEXTURE_OUT_SC = `${TEXTURE_CATEGORY}/Out-SC-Textures`;
export const TEXTURE_OUT = `${TEXTURE_CATEGORY}/Out-Textures`;

export const COMPRESSION_CATEGORY = `./Compression`;
export const COMPRESSION_IN_FILE = `${COMPRESSION_CATEGORY}/In-Compressed-files`;
export const COMPRESSION_IN = `${COMPRESSION_CATEGORY}/In-files`;
export const COMPRESSION_OUT_FILE = `${COMPRESSION_CATEGORY}/Out-Compressed-files`;
export const COMPRESSION_OUT = `${COMPRESSION_CATEGORY}/Out-files`;

export const DIRS = [
	TEXTURE_CATEGORY,
	TEXTURE_IN_SC,
	TEXTURE_IN,
	TEXTURE_OUT_SC,
	TEXTURE_OUT,

	COMPRESSION_CATEGORY,
	COMPRESSION_IN_FILE,
	COMPRESSION_IN,
	COMPRESSION_OUT_FILE,
	COMPRESSION_OUT
];
