export declare const TEXTURE_CATEGORY = "./SC-Textures";
export declare const TEXTURE_IN_SC: string;
export declare const TEXTURE_IN: string;
export declare const TEXTURE_OUT_SC: string;
export declare const TEXTURE_OUT: string;
export declare const COMPRESSION_CATEGORY = "./Compression";
export declare const COMPRESSION_IN_FILE: string;
export declare const COMPRESSION_IN: string;
export declare const COMPRESSION_OUT_FILE: string;
export declare const COMPRESSION_OUT: string;
export declare const MERGE_CATEGORY = "./SC-Merge";
export declare const MERGE_IN: string;
export declare const MERGE_OUT: string;
export declare const DIRS: string[];
